  try {
      throw new Exception();
  } catch(Exception) {
      assert false ;
  }